pluginManagement {
    repositories {
        maven { url uri('./local-plugin-repo') }
        google()
        maven { url 'https://repo1.maven.org/maven2/' }
        maven { url 'https://plugins.gradle.org/m2' }
        gradlePluginPortal()
    }
}

rootProject.name = 'iSeaTree'

apply from: '../node_modules/react-native-unimodules/gradle.groovy'
includeUnimodulesProjects()

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle");
applyNativeModulesSettingsGradle(settings)

include ':app'
