require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Installations'
pod 'Firebase/Performance'
pod 'Firebase/Installations'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Messaging'
pod 'Firebase/Functions'
pod 'Firebase/Storage'
pod 'RNSha256', :path => '../node_modules/react-native-sha256'

target 'iSeaTree' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target_is_resource_bundle = target.respond_to?(:product_type) && target.product_type == 'com.apple.product-type.bundle'
      target.build_configurations.each do |config|
        if target_is_resource_bundle
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
          config.build_settings['CODE_SIGNING_IDENTITY'] = '-'
          config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = '-'
        end
      end
    end
  end
end


