require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Installations'
pod 'Firebase/Performance'
pod 'Firebase/Installations'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Messaging'
pod 'Firebase/Functions'
pod 'Firebase/Storage'

target 'iSeaTree' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

end
post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
          # config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      end
  end
end
